language: node_js
before_install: yarn config set workspaces-experimental true && yarn config set ignore-engines true
script: yarn test
cache: yarn
node_js:
  - '12.4.0'

branches:
  only:
    - master
